services:
  db:
    image: mariadb:10.11
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: osticket
      MARIADB_USER: osticket
      MARIADB_PASSWORD: osticket
    volumes:
      - db:/var/lib/mysql

  osticket:
    build:
      context: .
      dockerfile: docker/osticket/Dockerfile
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./plugin:/var/www/html/include/plugins:rw
      - ./.osticket/include/ost-config.php:/var/www/html/include/ost-config.php:rw
      - attachments:/var/www/html/attachments

volumes:
  db:
  attachments:
